---
title: CDPR-Copper for Comps
output:
  html_document:
    keep_md: true
---

## Setup
```{r Setup}

library(ggplot2)
library(plotly)
library(tidyverse)
library(scales) # for viz
library(RColorBrewer) # for viz

# For spatial work
library(sf)

```

## Read in Data: CDPR
```{r Read in Data: CDPR}

cdpr <- read_csv("D:/LocalRepos/CDPR-Copper_ExternalData/CalPIP_Cu_2008-2021.csv")

```

## CDPR Data Clean-up
### Clean up SITES and Columns
```{r CDPR: Keep Any Ag SITES and Keep ONLY rice SITES}

# Counts of site types
sites <- cdpr %>% count(SITE_NAME)

# create df with ag-related SITE only, including any outdoor-related plant production
allCu <- cdpr %>% 
  filter(SITE_NAME != "" & 
           SITE_NAME != "AIRPORTS AND LANDING FIELDS (RUNWAYS, ETC.)" & 
           SITE_NAME != "ANTIFOULING TREATMENT SITES (ALL OR UNSPEC)" & 
           SITE_NAME != "AQUATIC AREAS, WATER AREAS (ALL OR UNSPEC)" & 
           SITE_NAME != "AQUATIC SITE - INDUSTRIAL USE (COMBINED SITE)" & 
           SITE_NAME != "BUILDINGS AND STRUCTURES (NON-AG OUTDOOR)" & 
           SITE_NAME != "COMMODITY FUMIGATION" & 
           SITE_NAME != "COUNTY AG. COMM. SALES" & 
           SITE_NAME != "FUMIGATION, OTHER" & 
           SITE_NAME != "HUMAN DRINKING WATER SYSTEMS (POTABLE)" & 
           SITE_NAME != "INDUSTRIAL PROCESSING WATER" & 
           SITE_NAME != "INDUSTRIAL WASTE DISPOSAL SYSTEMS, DISPOSAL WATER" & 
           SITE_NAME != "IRRIGATION SYSTEMS (DITCHES, CANAL BANKS, ETC.)" & 
           SITE_NAME != "LANDSCAPE MAINTENANCE" & 
           SITE_NAME != "N-GRNHS GRWN CUT FLWRS OR GREENS" & 
           SITE_NAME != "N-GRNHS GRWN PLANTS IN CONTAINERS" & 
           SITE_NAME != "N-GRNHS GRWN TRNSPLNT/PRPGTV MTRL" & 
           # SITE_NAME != "N-OUTDR CONTAINER/FLD GRWN PLANTS" & 
           # SITE_NAME != "N-OUTDR GRWN CUT FLWRS OR GREENS" & 
           # SITE_NAME != "N-OUTDR GRWN TRNSPLNT/PRPGTV MTRL " & 
           SITE_NAME != "ORNAMENTAL TURF (ALL OR UNSPEC)" & 
           SITE_NAME != "PUBLIC HEALTH PEST CONTROL" & 
           SITE_NAME != "RECREATIONAL AREAS, TENNIS COURTS, PARKS, ETC." & 
           SITE_NAME != "REGULATORY PEST CONTROL" & 
           SITE_NAME != "RESEARCH COMMODITY" & 
           SITE_NAME != "RIGHTS OF WAY" & 
           # SITE_NAME != "SOIL APPLICATION, PREPLANT-OUTDOOR (SEEDBEDS,ETC.)" & 
           SITE_NAME != "STRUCTURAL PEST CONTROL" & 
           SITE_NAME != "TURF, GOLF COURSE (FAIRWAYS, GREENS, ROUGH)" & 
           # SITE_NAME != "UNCULTIVATED AGRICULTURAL AREAS (ALL OR UNSPEC)" & 
           SITE_NAME != "UNCULTIVATED NON-AG AREAS (ALL OR UNSPEC)" & 
           SITE_NAME != "VERTEBRATE PEST CONTROL" & 
           SITE_NAME != "WOOD PROTECTION TREATMENTS (ALL OR UNSPECIFIED)")


# Create df with rice-related SITE values only (total 14731 rows)
rice <- cdpr %>%
  filter(SITE_NAME == "RICE (ALL OR UNSPEC)" | SITE_NAME == "RICE, WILD (GRAIN CROP)")


# Remove unnecessary columns
allCu <- allCu[,-c(1, 3)]
rice <- rice[,-c(1, 3)]

# Remove NA, blank values
sum(is.na(allCu$POUNDS_CHEMICAL_APPLIED))
sum(is.na(allCu$APPLICATION_MONTH))
sum(allCu$POUNDS_CHEMICAL_APPLIED == "")
sum(allCu$APPLICATION_MONTH == "")

sum(is.na(rice$POUNDS_CHEMICAL_APPLIED))
sum(is.na(rice$APPLICATION_MONTH))
sum(rice$POUNDS_CHEMICAL_APPLIED == "")
sum(rice$APPLICATION_MONTH == "")

allCu <- allCu %>%
  filter(!is.na(POUNDS_CHEMICAL_APPLIED)) %>%
  filter(!is.na(APPLICATION_MONTH))

rice <- rice %>%
  filter(!is.na(POUNDS_CHEMICAL_APPLIED)) %>%
  filter(!is.na(APPLICATION_MONTH))
```

### Clean up column info
```{r Clean up column info}
# Change all to title case and assign as factors

# allCu
allCu$APPLICATION_MONTH <- factor(str_to_title(allCu$APPLICATION_MONTH),
                                  levels = c("January", "February", "March", "April", "May", "June", 
                                             "July", "August", "September", "October", "November", "December"))
allCu$COUNTY_NAME <- factor(str_to_title(allCu$COUNTY_NAME))
allCu$CHEMICAL_NAME <- factor(str_to_title(allCu$CHEMICAL_NAME))
allCu$SITE_NAME <- factor(str_to_title(allCu$SITE_NAME))
allCu$PRODUCT_NAME <- factor(str_to_title(allCu$PRODUCT_NAME))

# rice
rice$APPLICATION_MONTH <- factor(str_to_title(rice$APPLICATION_MONTH),
                                  levels = c("January", "February", "March", "April", "May", "June", 
                                             "July", "August", "September", "October", "November", "December"))
rice$COUNTY_NAME <- factor(str_to_title(rice$COUNTY_NAME))
rice$CHEMICAL_NAME <- factor(str_to_title(rice$CHEMICAL_NAME))
rice$SITE_NAME <- factor(str_to_title(rice$SITE_NAME))
rice$PRODUCT_NAME <- factor(str_to_title(rice$PRODUCT_NAME))

```

### Split COMTRS into matching columns in PLSS df
```{r Split COMTRS}

# COMTRS stands for: county/meridian/township/range/section
# Non-ag pesticide use reports do not have this because they are reported at county level only.

# Digits 1&2 are county, 3rd = meridian, 4-6 = Township (xxN, xxS), 7-9 = Range (xxE, xxW), 10-11 = Section
# To match PLSS data, start all townships with "T", all ranges with "R", and abbreviate meridians as "HM", "MDM", "SBM", where "HM" = Humboldt, "MDM" = Mount Diablo, and "SBM" = San Bernardino
# So convert from CDPR to PLSS as meridan of: "H" --> "HM", "M" --> "MDM", & "S" --> "SBM"


allCu <- allCu %>%
  mutate(County_Num = str_sub(COMTRS, start = 1, end = 2),
         Meridian = str_sub(COMTRS, start = 3, end = 3),
         Township = str_sub(COMTRS, start = 4, end = 6),
         Range = str_sub(COMTRS, start = 7, end = 9),
         Section = str_sub(COMTRS, start = 10, end = 11))

# Further conversion to match PLSS (separated from above for clarity)
# Create a "TownshipRa" column as well
allCu <- allCu %>%
  mutate(Meridian = case_when(Meridian == "H" ~ "HM",
                              Meridian == "M" ~ "MDM",
                              Meridian == "S" ~ "SBM"),
         # Township = str_c("T", Township),
         # Range = str_c("R", Range),
         TownshipRa = str_c(Township, Range, sep = " "))


# Repeat for rice
rice <- rice %>%
  mutate(County_Num = str_sub(COMTRS, start = 1, end = 2),
         Meridian = str_sub(COMTRS, start = 3, end = 3),
         Township = str_sub(COMTRS, start = 4, end = 6),
         Range = str_sub(COMTRS, start = 7, end = 9),
         Section = str_sub(COMTRS, start = 10, end = 11))

# Further conversion to match PLSS (separated from above for clarity)
rice <- rice %>%
  mutate(Meridian = case_when(Meridian == "H" ~ "HM",
                              Meridian == "M" ~ "MDM",
                              Meridian == "S" ~ "SBM"),
         # Township = str_c("T", Township),
         # Range = str_c("R", Range),
         TownshipRa = str_c(Township, Range, sep = " "))
```


### Summary Statistics: Rice 
```{r Summary Stats: Rice}

# Bar graph of summary pounds applied by county and year
rice %>%
  group_by(YEAR, COUNTY_NAME) %>%
  summarize(POUNDS_CHEMICAL_APPLIED) %>%
  ggplot(aes(x = COUNTY_NAME, y = POUNDS_CHEMICAL_APPLIED)) + 
  geom_boxplot() +
  facet_wrap(~YEAR) + 
  theme_bw()

rice %>%
  group_by(YEAR, COUNTY_NAME) %>%
  summarize(POUNDS_CHEMICAL_APPLIED) %>%
  ggplot(aes(x = factor(YEAR), y = POUNDS_CHEMICAL_APPLIED)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~COUNTY_NAME) +
  theme_bw()

rice %>%
  group_by(YEAR, COUNTY_NAME) %>%
  summarize(mean = mean(sum(POUNDS_CHEMICAL_APPLIED)))

test <- 
rice %>%
  group_by(YEAR, COUNTY_NAME) %>%
  summarize(sum = sum(POUNDS_CHEMICAL_APPLIED)) %>%
  group_by(COUNTY_NAME) %>%
  summarize(mean = mean(sum))

test %>%
  group_by(COUNTY_NAME) %>%
  summarize(mean = mean(sum))
```


```{r Read in Spatial Data: PLSS}

# This is not the best dataset
# plss <- st_read("./Data/Spatial/Public_Land_Survey_System/Public_Land_Survey_System_(PLSS)%3A_Sections.shp")

# This one is better, because it includes county names and numbers already
plss <- st_read("./Data/Spatial/Statewide_CA_PLSS_NAD83AlbersCA/Statewide_CA_PLSS_NAD83AlbersCA.shp")


# plss[1:10000,]
# plot(plss[,"TownshipRa"])


# check geometry type
# object type is MULTIPOLYGON
# The 18 levels are the possible object types that it could be
# st_geometry_type(plss)
# plss[1]


# check CRS of the file data
# See that it is in WGS84, Pseudo-mercator
# st_crs(plss)

# To get extent of the file
# gives furthest N, S, E, W edges of the data
# st_bbox(plss)

# View all metadata and attributes, print to screen
# plss
# Or the first row
# plss[1,9]

# To plot, need to use geom_sf and coord_sf
# Note, this is MUCH FASTER than plot(plss) or using ggplot without geom_sf & coord_sf
# ggplotly(
# ggplot() +
#   geom_sf(data = plss_co) +
#   theme_bw() +
#   coord_sf()
# )

# View contents of a specific column, here just unique values
# unique(plss$TownshipRa)


# Group geometries by county
plss_co <- plss %>%
  group_by(NAME) %>%
  summarize(geometry = st_union(geometry))

# Group geometries by TownshipRange
plss_tr <- plss %>%
  mutate(TownshipRa = str_c(TOWNSHIP, RANGE, sep = " ")) %>%
  group_by(NAME, TownshipRa) %>%
  summarize(geometry = st_union(geometry))
```


## Remove CDPR and PLSS objects to save memory
```{r Remove CDPR and PLSS}
rm(cdpr, plss)

```


## Creating NA data for every township/range and County
```{r}

# Will need to create NA data for every township/section to be able to map the data

# check all townships and ranges shown in PLSS, allCu, rice dfs
# plssTR <- plss %>% count(TownshipRa)    # 3549 rows
# allCuTR <- allCu %>% count(TownshipRa)  # 1156 rows
# riceTR <- rice %>% count(TownshipRa)    # 120 rows


```


## Merging Rice Data to PLSS
```{r Merging rice data to plss}

# First need to summarize POUNDS_CHEMICAL_APPLIED by year and Township
rice_sum_tr <- rice %>%
  drop_na(Meridian) %>%
  group_by(YEAR, COUNTY_NAME, TownshipRa) %>%
  summarise(sum_lbs_applied = sum(POUNDS_CHEMICAL_APPLIED))

# Add COMTRS column to rice_sum, DO I NEED TO DO THIS??
# rice_sum_t <- left_join(x = rice_sum_t, y = rice[, c("COMTRS", "COUNTY_NAME", "Township")], by = "Township")


# Joined dataset with one year
plss_rice_tr2021 <- left_join(x = plss_tr, 
                              y = rice_sum_tr[rice_sum_tr$YEAR == 2021, ], 
                              by = c("TownshipRa" = "TownshipRa", "NAME" = "COUNTY_NAME"))
# plss_rice <- plss_rice %>%
#   distinct(.keep_all = TRUE) 

# plss_rice_t <- plss_rice_t %>%
#   complete(TOWNSHIP, geometry, YEAR) %>%
#   drop_na(YEAR)

plss_rice_tr2021 <- plss_rice_tr2021 %>%
  mutate(sum_lbs_applied = replace_na(sum_lbs_applied, 0))



# Test to print just one county, facet by Year
ggplot() +
  geom_sf(data = plss_rice_tr2021, 
          aes(geometry = geometry, fill = sum_lbs_applied)) + 
  theme_bw() + 
  coord_sf() +
  # facet_wrap(~YEAR) +
  scale_fill_distiller(name = "Total Pounds",
                     labels = comma,
                     trans = "reverse",
                     palette = "Oranges")


```


## Merging allCu Data to PLSS
```{r Merging rice data to plss}

# First need to summarize POUNDS_CHEMICAL_APPLIED by year and Township
allCu_sum_tr <- allCu %>%
  drop_na(Meridian) %>%
  group_by(YEAR, COUNTY_NAME, TownshipRa) %>%
  summarise(sum_lbs_applied = sum(POUNDS_CHEMICAL_APPLIED))

# Add COMTRS column to rice_sum, DO I NEED TO DO THIS??
# rice_sum_t <- left_join(x = rice_sum_t, y = rice[, c("COMTRS", "COUNTY_NAME", "Township")], by = "Township")


# Joined dataset with one year
plss_allCu_tr2021 <- left_join(x = plss_tr, 
                              y = allCu_sum_tr[allCu_sum_tr$YEAR == 2021, ], 
                              by = c("TownshipRa" = "TownshipRa", "NAME" = "COUNTY_NAME"))

plss_allCu_tr2008 <- left_join(x = plss_tr, 
                              y = allCu_sum_tr[allCu_sum_tr$YEAR == 2008, ], 
                              by = c("TownshipRa" = "TownshipRa", "NAME" = "COUNTY_NAME"))
# plss_rice <- plss_rice %>%
#   distinct(.keep_all = TRUE) 

# plss_rice_t <- plss_rice_t %>%
#   complete(TOWNSHIP, geometry, YEAR) %>%
#   drop_na(YEAR)



# Actually looks better without converting to 0
# Or need to change visualization in ggplot so that 0 values are colored grey
plss_allCu_tr2021 <- plss_allCu_tr2021 %>%
  mutate(sum_lbs_applied = replace_na(sum_lbs_applied, 0))

plss_allCu_tr2008 <- plss_allCu_tr2008 %>%
  mutate(sum_lbs_applied = replace_na(sum_lbs_applied, 0))


# Test to print 
ggplot() +
  geom_sf(data = plss_allCu_tr2021, 
          aes(geometry = geometry, fill = sum_lbs_applied)) + 
  theme_bw() + 
  coord_sf() +
  # facet_wrap(~YEAR) +
  scale_fill_distiller(name = "Total Pounds in 2021",
                     labels = comma,
                     trans = "reverse",
                     palette = "Oranges")
```

```{r}
# Make joined datasets for each year, then bind_rows

# Summarize for whole state
allCu_sum <- allCu %>%
  group_by(YEAR, COUNTY_NAME, COMTRS) %>%
  summarise(sum_lbs_applied = sum(POUNDS_CHEMICAL_APPLIED))

plss_allCu2008 <- full_join(x = plss, y = allCu_sum[allCu_sum$YEAR == "2008",], by = c("CO_MTRS" = "COMTRS"))
plss_allCu2008 <- plss_allCu2008 %>%
  complete(CO_MTRS, YEAR)

plss_rice2009 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2009",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2009 <- plss_rice2009 %>%
  distinct(.keep_all = TRUE)

plss_rice2010 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2010",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2010 <- plss_rice2010 %>%
  distinct(.keep_all = TRUE)      

plss_rice2011 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2011",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2011 <- plss_rice2011 %>%
  distinct(.keep_all = TRUE)

plss_rice2012 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2012",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2012 <- plss_rice2012 %>%
  distinct(.keep_all = TRUE)

plss_rice2013 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2013",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2013 <- plss_rice2013 %>%
  distinct(.keep_all = TRUE)

plss_rice2014 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2014",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2014 <- plss_rice2014 %>%
  distinct(.keep_all = TRUE)

plss_rice2015 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2015",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2015 <- plss_rice2015 %>%
  distinct(.keep_all = TRUE)

plss_rice2016 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2016",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2016 <- plss_rice2016 %>%
  distinct(.keep_all = TRUE)

plss_rice2017 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2017",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2017 <- plss_rice2017 %>%
  distinct(.keep_all = TRUE)

plss_rice2018 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2018",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2018 <- plss_rice2018 %>%
  distinct(.keep_all = TRUE)

plss_rice2019 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2019",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2019 <- plss_rice2019 %>%
  distinct(.keep_all = TRUE)

plss_rice2020 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2020",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2020 <- plss_rice2020 %>%
  distinct(.keep_all = TRUE)

plss_rice2021 <- full_join(x = plss, y = rice_sum[rice_sum$YEAR == "2021",], by = c("CO_MTRS" = "COMTRS"))
plss_rice2021 <- plss_rice2021 %>%
  distinct(.keep_all = TRUE)

# Test to print just one county from each year's dataset
ggplot() +
  geom_sf(data = plss_allCu2008, 
          aes(geometry = geometry, fill = sum_lbs_applied)) + 
  theme_bw() + 
  coord_sf() +
  scale_fill_distiller(name = "Total Pounds",
                     labels = comma,
                     trans = "reverse", 
                     palette = "Oranges")


plss_rice_all <- bind_rows(plss_rice2008, plss_rice2009, plss_rice2010, plss_rice2011, plss_rice2012,
                           plss_rice2013, plss_rice2014, plss_rice2015, plss_rice2016, plss_rice2017,
                           plss_rice2018, plss_rice2019, plss_rice2020, plss_rice2021)

plss_rice_mean <- plss_rice_all %>%
  group_by(CO_MTRS, NAME) %>%
  summarize(mean = mean(sum_lbs_applied))


ggplot() +
  geom_sf(data = plss_rice_mean[plss_rice_all$NAME == "Butte",], aes(fill = mean(sum_lbs_applied))) + 
  theme_bw() + 
  coord_sf() +
  # facet_wrap(~YEAR) + 
  scale_fill_distiller(name = "Total Pounds",
                     labels = comma,
                     trans = "reverse", 
                     palette = "Oranges")
```

